<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://providers/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="CompositeProvider5" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="CompositeProvider5">
  <import location="http://130.211.55.72:9080/CompositeProvider5-sun-http-binding/23.251.142.243_8080/Provider/Provider5.wsdl" namespace="http://providers/">
    </import>
  <portType name="dummyCasaPortType">
  </portType>
  <binding name="casaBinding1" type="ns:Provider5">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="listenner">
      <soap:operation/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
    <operation name="hello">
      <soap:operation/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="CompositeProvider5Service1">
    <port binding="tns:casaBinding1" name="casaPort1">
      <soap:address location="http://130.211.55.72:9080/CompositeProvider5Service1/casaPort1"/>
    </port>
  </service>
</definitions>
